### ISSUE TITLE
Do we actually want to serve all of our story pages as AMP-only?

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/tiny-news-demo#37]
Been doing some reading about AMP, and I'm not sure we want to lock in like this. Especially since it's [not going to be required to get at the top of search results](https://www.theverge.com/2020/5/28/21272543/google-search-results-page-experience-load-time-contentfu-paint-layout-shift-top-stories-amp) starting next year.

Anyway, just putting the question here for discussion. I'm not sure how I feel yet.

**Comment by jacqui** [comment]
Personally, I've never been a big fan of AMP but I'm trying to be open-minded about it. I mean, AMP restricts what you can do on the web (by design) which can be problematic when you're trying to push cool visualisations - or okay, at least it was when I first tried it. So that was my intro to it.

I heard about the search ranking, but I'll do some more research today on the current state of AMP, pros & cons.

**Comment by jacqui** [comment]
I see that google's announced the release of a new project aimed at quantifying website performance & general health called Web Vitals. It includes a small javascript library for measuring this on your site. I'm opening a new issue to get this setup on the tiny news site.

**Comment by jacqui** [comment]
Just to recap that we are now:

* serving articles with regular markup as a default
* offering AMP versions of articles at `${articleURL}/amp/`
* measuring site health with web-vitals
