### ISSUE TITLE
High-level categorization of stories, translate to nav bar

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/tiny-news-demo#61]
News organizations should be able to define their high-level verticals/categories of coverage. Those should be reflected in the website's navigation.

**Comment by jacqui** [comment]
Would these categories map to stories? Are they different than tags (it sounds like they are)? Would they exist purely for the nav?

## Create high-level categories

This can be done in `gatsby-config.js` easily:

```
module.exports = {
  siteMetadata: {
    categories: [
      {label: "Top Stories", link: "/top-stories"},
      {label: "Pandemic", link: "/pandemic"},
      {label: "Video", link: "/video"}
    ]
  }
}
```

Pros: categories accessible via graphql; configurable per-tinynewsco
Cons: need to edit a source file to alter; no assurance that specified links exist*

We could do an archieml type solution, where each google drive folder has a special "settings" file that gets sourced on site start/publishing:

```
[categories]

Label: News
Link: /news/

Label: Pandemic
Link: /pandemic/

Label: Video
Link: /video/

Label: Subscribe
Link: /subscribe/
```

Pros: easy to edit; configurable per-tinynewsco
Cons: still requires a restart/repub; requires writing our own [source plugin](https://www.gatsbyjs.org/docs/creating-a-source-plugin/) or hacking the gatsby google-docs source importer we're using.

Finally, another option is to make a page in `/tinycms` that manages the nav, where you list a label and link for each category. It could write to a settings file in the google drive, or I guess to another google-hosted storage.

I'm trying to come up with solutions that don't require a separate database, though ;)

## Link categories to articles

To associate these categories with stories, we could handle that similarly to tagging in /tinycms.

The "metadata editor" could have a dropdown for "Category" prefilled, select one or more. This would be persisted to each document's description.

## Creating category landing pages

We could easily loop over these high-level categories in `gatsby-node.js` (especially if this data is in graphql) and call gatsby's `createPage()` to ensure these destination links exist. This is how the tag-specific article list pages work.

And we could extend this so a particular category could use a particular template, like, "Latest Stories" uses a "new_stories.js" template that has a graphql query for X stories published in the last Y hours.


## Other nav links

I could see wanting other things in the navigation, like links to existing pages or to off-site destinations. Example, add "Subscribe" -> /subscribe to the nav. I'm thinking over how we'd manage this (select from a list of existing pages, vs create new ones similar to tag pages?).

---


Of course, this whole thing gets slightly complicated due to how the gatsby build process works - meaning, the site needs to be restarted and/or rebuilt & published in order for these changes to show up... depending on how we implement all of the above, that is.

**Comment by TylerFisher** [comment]
I think my preference is to have a page in tinyCMS that defines categories for you and writes that somewhere in Google Drive. That automatically gets built into your navbar, and built into a dropdown for each story editor so you can associate each story with a category.

**Comment by jacqui** [comment]
wrapped up in PRs 87, 89 and 90
