### ISSUE TITLE
Homepage management

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/tiny-news-demo#62]
How do news organizations manage their homepage? What are they able to do?

At minimum, they should be able to choose the featured story at the top of the page. This is likely something that becomes a part of the tiny CMS set of forms.

**Comment by jacqui** [comment]
This seems more straightforward to me than the high-level categories issue :) Though it's easy to go crazy with homepage management.

For a start we could accomplish the featured story on the homepage by adding a boolean flag to the document description data (`featured: true`) and then query for it while building the homepage.

This warrants its own UI (under /tinycms), so that selecting a featured story would mark all other stories as `featured: false` behind the scenes. 

Hopefully, that's achievable by finding the current featured story (graphql lookup) and then writing to google drive with the updated description for that story's document.

**Comment by TylerFisher** [comment]
Yup, that makes sense for placing the featured image. It also gives us the flexibility to add new homepage features if they arise (maybe different featured story packages/layouts for different moments).
